### ISSUE TITLE
How to get location address from command line?

### ISSUE THREAD

**Issue by maxlpy** [jayantdhawan/yelp-targeted-ads#1]
Because location is only one parameter in our program, but the location address is a string which usually separated by space or comma. In order to fit our program, you can add a underline between the location address words, such as:
- raleign, nc -> raleigh_nc
- 530 Brookline Blvd PA 15226 -> 530_Brookline_Blvd_PA_15226

**Comment by KeleiAzz** [comment]
In the `loadDataFromFile.py` I added a `load_business_info()`, it will create a dict with business id as key, and its address and categories as value.

**Comment by jayantdhawan** [comment]
Just to clarify what Fred noted, he meant the input address given to our program. So for example:

`python targetedAdsRecommender.py 8J4IIYcqBlFch8T90N923A 10 530_Brookline_Blvd_PA_15226`

**Comment by maxlpy** [comment]
We have figured out a better solution that just use double quotes. Since command line parser can read the content in the double quotes as one value.
